<a href="https://colab.research.google.com/github/Mitvirani310/CE156_Mit_Virani/blob/main/Lab7/CE156_ML_Lab7_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import io
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
from google.colab import drive
drive.mount("/content/drive")
data = pd.read_csv("/content/drive/My Drive/Sem 6/ML/Lab7/BuyComputer.csv")
print("\nData :\n",data)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Data :
       User ID  Age  EstimatedSalary  Purchased
0    15624510   19            19000          0
1    15810944   35            20000          0
2    15668575   26            43000          0
3    15603246   27            57000          0
4    15804002   19            76000          0
..        ...  ...              ...        ...
395  15691863   46            41000          1
396  15706071   51            23000          1
397  15654296   50            20000          1
398  15755018   36            33000          0
399  15594041   49            36000          1

[400 rows x 4 columns]


In [ ]:
data.drop(columns=['User ID',],axis=1,inplace=True)
data.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [ ]:
#Declare label as last column in the source file
features_Cols=['Age' ,'EstimatedSalary']
label = data.iloc[:, -1].values
X = data.iloc[:, :-1].values


print(label)
print(X)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]
[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 

In [ ]:
# Splitting data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split(X,label,test_size=0.1)
print(X_train)
print(X_test)
print(y_train)
print(y_test)


[[    57  74000]
 [    45 131000]
 [    27  31000]
 [    33 113000]
 [    23  28000]
 [    35  39000]
 [    33  28000]
 [    48 134000]
 [    35  97000]
 [    52 150000]
 [    42  80000]
 [    20  23000]
 [    31  58000]
 [    35  23000]
 [    31  76000]
 [    25  22000]
 [    29  43000]
 [    51 134000]
 [    40  60000]
 [    26  32000]
 [    36  63000]
 [    41  79000]
 [    34 112000]
 [    45  32000]
 [    41  72000]
 [    46  32000]
 [    31  89000]
 [    45  22000]
 [    54  70000]
 [    32 117000]
 [    59  76000]
 [    32 150000]
 [    32 100000]
 [    35  60000]
 [    26  16000]
 [    35  55000]
 [    27 137000]
 [    49  89000]
 [    59  42000]
 [    33  69000]
 [    32 120000]
 [    48  41000]
 [    60  42000]
 [    37 144000]
 [    28  87000]
 [    30  79000]
 [    33  60000]
 [    36  54000]
 [    34  43000]
 [    47  50000]
 [    41  63000]
 [    39 122000]
 [    50  44000]
 [    41  51000]
 [    41  72000]
 [    36 125000]
 [    22  55000]
 [    19  26000]
 [    25  3300

In [ ]:
# Sacaling data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)
print(X_test)

[[ 1.87660097  0.13145107]
 [ 0.72127588  1.83112091]
 [-1.01171177 -1.15075599]
 [-0.43404922  1.29438306]
 [-1.39682013 -1.2402123 ]
 [-0.24149504 -0.91220584]
 [-0.43404922 -1.2402123 ]
 [ 1.01010715  1.92057721]
 [-0.24149504  0.81728276]
 [ 1.39521552  2.39767752]
 [ 0.4324446   0.31036369]
 [-1.68565141 -1.38930615]
 [-0.6266034  -0.34564923]
 [-0.24149504 -1.38930615]
 [-0.6266034   0.19108861]
 [-1.20426595 -1.41912491]
 [-0.81915759 -0.79293077]
 [ 1.29893842  1.92057721]
 [ 0.23989042 -0.28601169]
 [-1.10798886 -1.12093722]
 [-0.14521795 -0.19655539]
 [ 0.33616751  0.28054492]
 [-0.33777213  1.2645643 ]
 [ 0.72127588 -1.12093722]
 [ 0.33616751  0.07181354]
 [ 0.81755297 -1.12093722]
 [-0.6266034   0.57873261]
 [ 0.72127588 -1.41912491]
 [ 1.5877697   0.012176  ]
 [-0.53032631  1.41365814]
 [ 2.06915516  0.19108861]
 [-0.53032631  2.39767752]
 [-0.53032631  0.90673907]
 [-0.24149504 -0.28601169]
 [-1.10798886 -1.59803753]
 [-0.24149504 -0.43510554]
 [-1.01171177  2.01003352]
 

In [ ]:
def sigmoid(z):
  sig = 1/(1+exp(-z))
  return sig

In [ ]:
def standardize(X_tr):
    for i in range(shape(X_tr)[1]):
        X_tr[:,i] = (X_tr[:,i] - np.mean(X_tr[:,i]))/np.std(X_tr[:,i])

In [ ]:
def F1_score(y,y_hat):
    tp,tn,fp,fn = 0,0,0,0
    for i in range(len(y)):
        if y[i] == 1 and y_hat[i] == 1:
            tp += 1
        elif y[i] == 1 and y_hat[i] == 0:
            fn += 1
        elif y[i] == 0 and y_hat[i] == 1:
            fp += 1
        elif y[i] == 0 and y_hat[i] == 0:
            tn += 1
    precision = tp/(tp+fp)
    recall = tp/(tp+fn)
    f1_score = 2*precision*recall/(precision+recall)
    return f1_score

In [ ]:
from numpy import log,dot,exp,shape
class LogidticRegression:
    def sigmoid(self,z):
        sig = 1/(1+exp(-z))
        return sig
    def initialize(self,X):
        weights = np.zeros((shape(X)[1]+1,1))
        X = np.c_[np.ones((shape(X)[0],1)),X]
        return weights,X
    def fit(self,X,y,alpha=0.002,iter=3000):
        weights,X = self.initialize(X)
        def cost(theta):
            z = dot(X,theta)
            cost0 = y.T.dot(log(self.sigmoid(z)))
            cost1 = (1-y).T.dot(log(1-self.sigmoid(z)))
            cost = -((cost1 + cost0))/len(y)
            return cost
        cost_list = np.zeros(iter,)
        for i in range(iter):
            weights = weights - alpha*dot(X.T,self.sigmoid(dot(X,weights))-np.reshape(y,(len(y),1)))
            cost_list[i] = cost(weights)
        self.weights = weights
        return cost_list
    def predict(self,X):
        z = dot(self.initialize(X)[1],self.weights)
        lis = []
        for i in self.sigmoid(z):
            if i>0.5:
                lis.append(1)
            else:
                lis.append(0)
        return lis

In [ ]:
standardize(X_train)
standardize(X_test)
obj1 = LogidticRegression()

In [ ]:
print(X_train)
print(y_train)
model= obj1.fit(X_train,y_train)
y_pred = obj1.predict(X_test)
y_tr = obj1.predict(X_train)

[[ 1.87660097  0.13145107]
 [ 0.72127588  1.83112091]
 [-1.01171177 -1.15075599]
 [-0.43404922  1.29438306]
 [-1.39682013 -1.2402123 ]
 [-0.24149504 -0.91220584]
 [-0.43404922 -1.2402123 ]
 [ 1.01010715  1.92057721]
 [-0.24149504  0.81728276]
 [ 1.39521552  2.39767752]
 [ 0.4324446   0.31036369]
 [-1.68565141 -1.38930615]
 [-0.6266034  -0.34564923]
 [-0.24149504 -1.38930615]
 [-0.6266034   0.19108861]
 [-1.20426595 -1.41912491]
 [-0.81915759 -0.79293077]
 [ 1.29893842  1.92057721]
 [ 0.23989042 -0.28601169]
 [-1.10798886 -1.12093722]
 [-0.14521795 -0.19655539]
 [ 0.33616751  0.28054492]
 [-0.33777213  1.2645643 ]
 [ 0.72127588 -1.12093722]
 [ 0.33616751  0.07181354]
 [ 0.81755297 -1.12093722]
 [-0.6266034   0.57873261]
 [ 0.72127588 -1.41912491]
 [ 1.5877697   0.012176  ]
 [-0.53032631  1.41365814]
 [ 2.06915516  0.19108861]
 [-0.53032631  2.39767752]
 [-0.53032631  0.90673907]
 [-0.24149504 -0.28601169]
 [-1.10798886 -1.59803753]
 [-0.24149504 -0.43510554]
 [-1.01171177  2.01003352]
 

In [ ]:
f1_score_tr = F1_score(y_train,y_tr)
f1_score_te = F1_score(y_test,y_pred)
print(f1_score_tr)
print(f1_score_te)

0.7522123893805309
0.7999999999999999


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score
LR = LogisticRegression(random_state = 0)
LR.fit(X_train,y_train)
y_pred=LR.predict(X_test)
print(f1_score(y_test,y_pred))

0.7647058823529413
